-- Create guests table for RSVP
CREATE TABLE IF NOT EXISTS guests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL DEFAULT '-',
  phone TEXT NOT NULL DEFAULT '-',
  confirmed TEXT NOT NULL CHECK (confirmed IN ('Sim', 'Não')),
  companions INTEGER NOT NULL DEFAULT 0,
  companion_names TEXT NOT NULL DEFAULT '',
  food_restrictions TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL DEFAULT '-',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Allow anonymous insert (anyone can RSVP)
ALTER TABLE guests ENABLE ROW LEVEL SECURITY;

-- Policy: anyone can insert
CREATE POLICY "Anyone can insert guests"
  ON guests FOR INSERT
  TO anon
  WITH CHECK (true);

-- Policy: only authenticated users can select
CREATE POLICY "Only authenticated can view guests"
  ON guests FOR SELECT
  TO authenticated
  USING (true);
